### ISSUE TITLE
Landing page footer credits are listed twice

### ISSUE THREAD

**Issue by rayi113** [RENCI/xDCIShare#51]
The footer on the landing page of xDCIShare lists the NSF credits twice, should only be once.
![xdcishare_footer_credits_2x](https://user-images.githubusercontent.com/2846017/28477002-2a4b9b72-6e20-11e7-852f-9be07cea6c48.png)

**Comment by cbcunc** [comment]
Changed in site configuration in admin interface which updates database. Dumped database and updated pg.development.sql so that change will show when database is rebuilt. For "production." where Ashok already has a student creating resources, I changed it manually through the admin interface again. Merged in #54.
